# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
