# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLog_Peso',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('data', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical log_ peso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Log_Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Log_Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao_nome', models.CharField(max_length=100, null=True)),
                ('descricao_refeicao', models.CharField(max_length=500)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='log_refeicao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Participante'),
        ),
        migrations.AddField(
            model_name='log_peso',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Participante'),
        ),
        migrations.AddField(
            model_name='historicallog_peso',
            name='participante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.Participante'),
        ),
    ]
