# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao_nome', models.CharField(max_length=100)),
                ('descricao_refeicao', models.CharField(max_length=500)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
