# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_log_refeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_refeicao',
            name='refeicao_nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
